import numpy as np
import sys
from PIL import Image
import matplotlib.pyplot as plt
sys.path.append('../')
from Bearing_defect_simulation.Bearing.Bearing import Bearing
from Bearing_defect_simulation.DES.Simulation import Simulation
from Bearing_defect_simulation.DES.Acquisition import Acquisition

def main():
    print("################ Comparision 2 model#############")
    print("#  This test validates that the frequency peaks  ")
    print("#  generated by the simulation are close to the ")
    print("#  theoretical peaks from the bearing defect ")
    print("#  equations")
    print("################################################### ")
    my_bearing=Bearing(a_rpm=2000)
    plt.axvline(my_bearing.get_BPFO_freq(), 0, 1,c='g', label='1x BPFO')
    plt.axvline(2*my_bearing.get_BPFO_freq(), 0, 1,c='m', label='2x BPFO')
    plt.axvline(3*my_bearing.get_BPFO_freq(), 0, 1,c='b', label='3x BPFO')
    plt.legend(title="Theoretical freq")
    my_acquisition=Acquisition(a_noise=0.0)
    my_simulation=Simulation(my_bearing,my_acquisition)
    my_simulation.start()
    my_simulation.get_results(format='as_graph',file_name='2000_rpm.png',
            title='Simulated 2000rpm')
    f1 = Image.open("2000_rpm.png").show()


if __name__ == '__main__':
    main()

